### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by SAGSSSS** [beingaryan/Blind-Assistance-Object-Detection-and-Navigation#1]
Can you please elaborate on how to integrate it to an android app ?

**Comment by beingaryan** [comment]
Yes, sure! Try using the Tensorflow Lite version of the object detecton. They've already developed a system pipeline code for Object Detection. Integrate Voice over modules in them using any of the Voice based API. Since it's an open-source project, you can start developing the project in android, and can commit to this repository.
